# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GN_Wavelet_GUI_Main_Panel.ui'
#
# Created: Fri Oct 16 15:58:31 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UiWaveletPanel(object):
    def setupUi(self, UiWaveletPanel):
        UiWaveletPanel.setObjectName(_fromUtf8("UiWaveletPanel"))
        UiWaveletPanel.resize(1064, 804)
        self.centralWidget = QtGui.QWidget(UiWaveletPanel)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.WgtGroupBox_Wavelet = QtGui.QGroupBox(self.centralWidget)
        self.WgtGroupBox_Wavelet.setGeometry(QtCore.QRect(10, 240, 421, 221))
        self.WgtGroupBox_Wavelet.setObjectName(_fromUtf8("WgtGroupBox_Wavelet"))
        self.WgtDSpinBox_WavDilStop_LBL = QtGui.QLabel(self.WgtGroupBox_Wavelet)
        self.WgtDSpinBox_WavDilStop_LBL.setGeometry(QtCore.QRect(40, 160, 81, 20))
        self.WgtDSpinBox_WavDilStop_LBL.setObjectName(_fromUtf8("WgtDSpinBox_WavDilStop_LBL"))
        self.WgtDSpinBox_WavDilStart_LBL = QtGui.QLabel(self.WgtGroupBox_Wavelet)
        self.WgtDSpinBox_WavDilStart_LBL.setGeometry(QtCore.QRect(40, 140, 81, 16))
        self.WgtDSpinBox_WavDilStart_LBL.setObjectName(_fromUtf8("WgtDSpinBox_WavDilStart_LBL"))
        self.WgtDSpinBox_WavDilStop = QtGui.QDoubleSpinBox(self.WgtGroupBox_Wavelet)
        self.WgtDSpinBox_WavDilStop.setGeometry(QtCore.QRect(90, 160, 69, 24))
        self.WgtDSpinBox_WavDilStop.setMaximum(10000.0)
        self.WgtDSpinBox_WavDilStop.setProperty("value", 100.0)
        self.WgtDSpinBox_WavDilStop.setObjectName(_fromUtf8("WgtDSpinBox_WavDilStop"))
        self.WgtDSpinBox_WavDilStep = QtGui.QDoubleSpinBox(self.WgtGroupBox_Wavelet)
        self.WgtDSpinBox_WavDilStep.setGeometry(QtCore.QRect(90, 190, 69, 24))
        self.WgtDSpinBox_WavDilStep.setProperty("value", 10.0)
        self.WgtDSpinBox_WavDilStep.setObjectName(_fromUtf8("WgtDSpinBox_WavDilStep"))
        self.WgtComboBox_ScaleVsFreq = QtGui.QComboBox(self.WgtGroupBox_Wavelet)
        self.WgtComboBox_ScaleVsFreq.setGeometry(QtCore.QRect(10, 60, 151, 26))
        self.WgtComboBox_ScaleVsFreq.setObjectName(_fromUtf8("WgtComboBox_ScaleVsFreq"))
        self.WgtComboBox_ScaleVsFreq.addItem(_fromUtf8(""))
        self.WgtComboBox_ScaleVsFreq.addItem(_fromUtf8(""))
        self.WgtComboBox_WavType = QtGui.QComboBox(self.WgtGroupBox_Wavelet)
        self.WgtComboBox_WavType.setGeometry(QtCore.QRect(10, 30, 151, 26))
        self.WgtComboBox_WavType.setObjectName(_fromUtf8("WgtComboBox_WavType"))
        self.WgtComboBox_WavType.addItem(_fromUtf8(""))
        self.WgtComboBox_WavType.addItem(_fromUtf8(""))
        self.WgtComboBox_WavType.addItem(_fromUtf8(""))
        self.WgtComboBox_WavType.addItem(_fromUtf8(""))
        self.WgtDSpinBox_WavDilStart = QtGui.QDoubleSpinBox(self.WgtGroupBox_Wavelet)
        self.WgtDSpinBox_WavDilStart.setGeometry(QtCore.QRect(90, 130, 69, 24))
        self.WgtDSpinBox_WavDilStart.setMaximum(10000.0)
        self.WgtDSpinBox_WavDilStart.setProperty("value", 1.0)
        self.WgtDSpinBox_WavDilStart.setObjectName(_fromUtf8("WgtDSpinBox_WavDilStart"))
        self.WgtDSpinBox_WavDilStep_LBL = QtGui.QLabel(self.WgtGroupBox_Wavelet)
        self.WgtDSpinBox_WavDilStep_LBL.setGeometry(QtCore.QRect(40, 190, 81, 16))
        self.WgtDSpinBox_WavDilStep_LBL.setObjectName(_fromUtf8("WgtDSpinBox_WavDilStep_LBL"))
        self.WgtWidget_Plot_WavMom = WgtPlot_Wavelet(self.WgtGroupBox_Wavelet)
        self.WgtWidget_Plot_WavMom.setGeometry(QtCore.QRect(170, 20, 231, 151))
        self.WgtWidget_Plot_WavMom.setObjectName(_fromUtf8("WgtWidget_Plot_WavMom"))
        self.WgtComboBox_CodeType = QtGui.QComboBox(self.WgtGroupBox_Wavelet)
        self.WgtComboBox_CodeType.setGeometry(QtCore.QRect(10, 90, 151, 26))
        self.WgtComboBox_CodeType.setObjectName(_fromUtf8("WgtComboBox_CodeType"))
        self.WgtComboBox_CodeType.addItem(_fromUtf8(""))
        self.WgtComboBox_CodeType.addItem(_fromUtf8(""))
        self.WgtComboBox_CodeType.addItem(_fromUtf8(""))
        self.WgtProgressBar1 = QtGui.QProgressBar(self.centralWidget)
        self.WgtProgressBar1.setGeometry(QtCore.QRect(580, 430, 181, 23))
        self.WgtProgressBar1.setProperty("value", 24)
        self.WgtProgressBar1.setObjectName(_fromUtf8("WgtProgressBar1"))
        self.WgtWidget_Plot_Scalogram = WgtPlot_Scalogram(self.centralWidget)
        self.WgtWidget_Plot_Scalogram.setGeometry(QtCore.QRect(450, 460, 581, 291))
        self.WgtWidget_Plot_Scalogram.setObjectName(_fromUtf8("WgtWidget_Plot_Scalogram"))
        self.WgtGroupBox_Sig_2 = QtGui.QGroupBox(self.centralWidget)
        self.WgtGroupBox_Sig_2.setGeometry(QtCore.QRect(10, 0, 421, 241))
        self.WgtGroupBox_Sig_2.setObjectName(_fromUtf8("WgtGroupBox_Sig_2"))
        self.WgtTabWidget_Sig = QtGui.QTabWidget(self.WgtGroupBox_Sig_2)
        self.WgtTabWidget_Sig.setGeometry(QtCore.QRect(10, 20, 401, 211))
        self.WgtTabWidget_Sig.setObjectName(_fromUtf8("WgtTabWidget_Sig"))
        self.WgtTabWidget_Page1_SigBuild = QtGui.QWidget()
        self.WgtTabWidget_Page1_SigBuild.setObjectName(_fromUtf8("WgtTabWidget_Page1_SigBuild"))
        self.WgtDSpinBox_SigSmpSec = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_SigSmpSec.setGeometry(QtCore.QRect(220, 0, 81, 24))
        self.WgtDSpinBox_SigSmpSec.setMaximum(100000.0)
        self.WgtDSpinBox_SigSmpSec.setProperty("value", 1000.0)
        self.WgtDSpinBox_SigSmpSec.setObjectName(_fromUtf8("WgtDSpinBox_SigSmpSec"))
        self.WgtDSpinBox_Sig2Stop = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig2Stop.setGeometry(QtCore.QRect(230, 80, 69, 24))
        self.WgtDSpinBox_Sig2Stop.setSingleStep(0.1)
        self.WgtDSpinBox_Sig2Stop.setProperty("value", 3.0)
        self.WgtDSpinBox_Sig2Stop.setObjectName(_fromUtf8("WgtDSpinBox_Sig2Stop"))
        self.WgtDSpinBox_Sig2Start = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig2Start.setGeometry(QtCore.QRect(150, 80, 69, 24))
        self.WgtDSpinBox_Sig2Start.setSingleStep(0.1)
        self.WgtDSpinBox_Sig2Start.setObjectName(_fromUtf8("WgtDSpinBox_Sig2Start"))
        self.WgtDSpinBox_Sig1Start = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Start.setGeometry(QtCore.QRect(150, 50, 69, 24))
        self.WgtDSpinBox_Sig1Start.setSingleStep(0.1)
        self.WgtDSpinBox_Sig1Start.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Start"))
        self.WgtDSpinBox_Sig1Freq = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Freq.setGeometry(QtCore.QRect(70, 50, 69, 24))
        self.WgtDSpinBox_Sig1Freq.setSingleStep(1.0)
        self.WgtDSpinBox_Sig1Freq.setProperty("value", 10.0)
        self.WgtDSpinBox_Sig1Freq.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Freq"))
        self.WgtDSpinBox_Sig1Stop = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Stop.setGeometry(QtCore.QRect(230, 50, 69, 24))
        self.WgtDSpinBox_Sig1Stop.setSingleStep(0.1)
        self.WgtDSpinBox_Sig1Stop.setProperty("value", 3.0)
        self.WgtDSpinBox_Sig1Stop.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Stop"))
        self.WgtDSpinBox_Sig1Start_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Start_LBL.setGeometry(QtCore.QRect(150, 30, 51, 16))
        self.WgtDSpinBox_Sig1Start_LBL.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Start_LBL"))
        self.WgtDSpinBox_SigLen = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_SigLen.setGeometry(QtCore.QRect(70, 0, 69, 24))
        self.WgtDSpinBox_SigLen.setProperty("value", 3.0)
        self.WgtDSpinBox_SigLen.setObjectName(_fromUtf8("WgtDSpinBox_SigLen"))
        self.WgtDSpinBox_Sig1Freq_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Freq_LBL.setGeometry(QtCore.QRect(10, 50, 41, 16))
        self.WgtDSpinBox_Sig1Freq_LBL.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Freq_LBL"))
        self.WgtDSpinBox_Sig2Freq = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig2Freq.setGeometry(QtCore.QRect(70, 80, 69, 24))
        self.WgtDSpinBox_Sig2Freq.setSingleStep(1.0)
        self.WgtDSpinBox_Sig2Freq.setProperty("value", 40.0)
        self.WgtDSpinBox_Sig2Freq.setObjectName(_fromUtf8("WgtDSpinBox_Sig2Freq"))
        self.WgtDSpinBox_Sig1Stop_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Stop_LBL.setGeometry(QtCore.QRect(230, 30, 51, 16))
        self.WgtDSpinBox_Sig1Stop_LBL.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Stop_LBL"))
        self.WgtDSpinBox_SigLen_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_SigLen_LBL.setGeometry(QtCore.QRect(0, 0, 61, 16))
        self.WgtDSpinBox_SigLen_LBL.setObjectName(_fromUtf8("WgtDSpinBox_SigLen_LBL"))
        self.WgtDSpinBox_SigSmpSec_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_SigSmpSec_LBL.setGeometry(QtCore.QRect(150, 0, 61, 16))
        self.WgtDSpinBox_SigSmpSec_LBL.setObjectName(_fromUtf8("WgtDSpinBox_SigSmpSec_LBL"))
        self.WgtDSpinBox_Sig2Freq_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig2Freq_LBL.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.WgtDSpinBox_Sig2Freq_LBL.setObjectName(_fromUtf8("WgtDSpinBox_Sig2Freq_LBL"))
        self.WgtComboBox_Noise = QtGui.QComboBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtComboBox_Noise.setGeometry(QtCore.QRect(70, 150, 131, 26))
        self.WgtComboBox_Noise.setObjectName(_fromUtf8("WgtComboBox_Noise"))
        self.WgtComboBox_Noise.addItem(_fromUtf8(""))
        self.WgtComboBox_Noise.addItem(_fromUtf8(""))
        self.WgtComboBox_Noise.addItem(_fromUtf8(""))
        self.WgtComboBox_Noise.addItem(_fromUtf8(""))
        self.WgtComboBox_Noise_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtComboBox_Noise_LBL.setGeometry(QtCore.QRect(10, 150, 41, 16))
        self.WgtComboBox_Noise_LBL.setObjectName(_fromUtf8("WgtComboBox_Noise_LBL"))
        self.WgtDSpinBox_Sig4Amp = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig4Amp.setGeometry(QtCore.QRect(310, 150, 69, 24))
        self.WgtDSpinBox_Sig4Amp.setSingleStep(0.1)
        self.WgtDSpinBox_Sig4Amp.setObjectName(_fromUtf8("WgtDSpinBox_Sig4Amp"))
        self.WgtDSpinBox_SigAmp_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_SigAmp_LBL.setGeometry(QtCore.QRect(310, 30, 51, 16))
        self.WgtDSpinBox_SigAmp_LBL.setObjectName(_fromUtf8("WgtDSpinBox_SigAmp_LBL"))
        self.WgtDSpinBox_Sig2Amp = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig2Amp.setGeometry(QtCore.QRect(310, 80, 69, 24))
        self.WgtDSpinBox_Sig2Amp.setSingleStep(0.1)
        self.WgtDSpinBox_Sig2Amp.setObjectName(_fromUtf8("WgtDSpinBox_Sig2Amp"))
        self.WgtDSpinBox_Sig1Amp = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig1Amp.setGeometry(QtCore.QRect(310, 50, 69, 24))
        self.WgtDSpinBox_Sig1Amp.setSingleStep(0.1)
        self.WgtDSpinBox_Sig1Amp.setProperty("value", 1.0)
        self.WgtDSpinBox_Sig1Amp.setObjectName(_fromUtf8("WgtDSpinBox_Sig1Amp"))
        self.WgtDSpinBox_Sig3Freq_LBL = QtGui.QLabel(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig3Freq_LBL.setGeometry(QtCore.QRect(10, 110, 41, 16))
        self.WgtDSpinBox_Sig3Freq_LBL.setObjectName(_fromUtf8("WgtDSpinBox_Sig3Freq_LBL"))
        self.WgtDSpinBox_Sig3Freq = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig3Freq.setGeometry(QtCore.QRect(70, 110, 69, 24))
        self.WgtDSpinBox_Sig3Freq.setSingleStep(1.0)
        self.WgtDSpinBox_Sig3Freq.setProperty("value", 40.0)
        self.WgtDSpinBox_Sig3Freq.setObjectName(_fromUtf8("WgtDSpinBox_Sig3Freq"))
        self.WgtDSpinBox_Sig3Start = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig3Start.setGeometry(QtCore.QRect(150, 110, 69, 24))
        self.WgtDSpinBox_Sig3Start.setSingleStep(0.1)
        self.WgtDSpinBox_Sig3Start.setObjectName(_fromUtf8("WgtDSpinBox_Sig3Start"))
        self.WgtDSpinBox_Sig3Stop = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig3Stop.setGeometry(QtCore.QRect(230, 110, 69, 24))
        self.WgtDSpinBox_Sig3Stop.setSingleStep(0.1)
        self.WgtDSpinBox_Sig3Stop.setProperty("value", 3.0)
        self.WgtDSpinBox_Sig3Stop.setObjectName(_fromUtf8("WgtDSpinBox_Sig3Stop"))
        self.WgtDSpinBox_Sig3Amp = QtGui.QDoubleSpinBox(self.WgtTabWidget_Page1_SigBuild)
        self.WgtDSpinBox_Sig3Amp.setGeometry(QtCore.QRect(310, 110, 69, 24))
        self.WgtDSpinBox_Sig3Amp.setSingleStep(0.1)
        self.WgtDSpinBox_Sig3Amp.setObjectName(_fromUtf8("WgtDSpinBox_Sig3Amp"))
        self.WgtTabWidget_Sig.addTab(self.WgtTabWidget_Page1_SigBuild, _fromUtf8(""))
        self.WgtTabWidget_Paget_LoadSig = QtGui.QWidget()
        self.WgtTabWidget_Paget_LoadSig.setObjectName(_fromUtf8("WgtTabWidget_Paget_LoadSig"))
        self.WgtLineEdit_FileName_In = QtGui.QLineEdit(self.WgtTabWidget_Paget_LoadSig)
        self.WgtLineEdit_FileName_In.setGeometry(QtCore.QRect(10, 110, 371, 21))
        self.WgtLineEdit_FileName_In.setObjectName(_fromUtf8("WgtLineEdit_FileName_In"))
        self.WgtLineEdit_FileName_In_LBL = QtGui.QLabel(self.WgtTabWidget_Paget_LoadSig)
        self.WgtLineEdit_FileName_In_LBL.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.WgtLineEdit_FileName_In_LBL.setObjectName(_fromUtf8("WgtLineEdit_FileName_In_LBL"))
        self.WgtPushButton_LoadFileSig = QtGui.QPushButton(self.WgtTabWidget_Paget_LoadSig)
        self.WgtPushButton_LoadFileSig.setGeometry(QtCore.QRect(270, 70, 113, 32))
        self.WgtPushButton_LoadFileSig.setObjectName(_fromUtf8("WgtPushButton_LoadFileSig"))
        self.WgtTabWidget_Sig.addTab(self.WgtTabWidget_Paget_LoadSig, _fromUtf8(""))
        self.WgtWidget_Plot_Sig1 = WgtPlot_Sig1(self.centralWidget)
        self.WgtWidget_Plot_Sig1.setGeometry(QtCore.QRect(450, 10, 511, 291))
        self.WgtWidget_Plot_Sig1.setWhatsThis(_fromUtf8(""))
        self.WgtWidget_Plot_Sig1.setObjectName(_fromUtf8("WgtWidget_Plot_Sig1"))
        self.WgtGroupBox_Wavelet_2 = QtGui.QGroupBox(self.centralWidget)
        self.WgtGroupBox_Wavelet_2.setGeometry(QtCore.QRect(10, 460, 421, 181))
        self.WgtGroupBox_Wavelet_2.setObjectName(_fromUtf8("WgtGroupBox_Wavelet_2"))
        self.WgtPushButton_WriteFiles = QtGui.QPushButton(self.WgtGroupBox_Wavelet_2)
        self.WgtPushButton_WriteFiles.setGeometry(QtCore.QRect(290, 140, 113, 32))
        self.WgtPushButton_WriteFiles.setObjectName(_fromUtf8("WgtPushButton_WriteFiles"))
        self.WgtCheckBox_Out_Sig_TXT = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Sig_TXT.setGeometry(QtCore.QRect(50, 40, 41, 20))
        self.WgtCheckBox_Out_Sig_TXT.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Sig_TXT.setObjectName(_fromUtf8("WgtCheckBox_Out_Sig_TXT"))
        self.WgtCheckBox_Out_Do_Wav = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Do_Wav.setGeometry(QtCore.QRect(90, 20, 61, 20))
        self.WgtCheckBox_Out_Do_Wav.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Do_Wav.setChecked(True)
        self.WgtCheckBox_Out_Do_Wav.setObjectName(_fromUtf8("WgtCheckBox_Out_Do_Wav"))
        self.WgtComboBox_Resolution = QtGui.QComboBox(self.WgtGroupBox_Wavelet_2)
        self.WgtComboBox_Resolution.setGeometry(QtCore.QRect(240, 20, 61, 26))
        self.WgtComboBox_Resolution.setObjectName(_fromUtf8("WgtComboBox_Resolution"))
        self.WgtComboBox_Resolution.addItem(_fromUtf8(""))
        self.WgtComboBox_Resolution.addItem(_fromUtf8(""))
        self.WgtComboBox_Resolution.addItem(_fromUtf8(""))
        self.WgtComboBox_Resolution.addItem(_fromUtf8(""))
        self.WgtComboBox_Resolution.addItem(_fromUtf8(""))
        self.WgtComboBox_Resolution_LBL = QtGui.QLabel(self.WgtGroupBox_Wavelet_2)
        self.WgtComboBox_Resolution_LBL.setGeometry(QtCore.QRect(180, 20, 61, 16))
        self.WgtComboBox_Resolution_LBL.setObjectName(_fromUtf8("WgtComboBox_Resolution_LBL"))
        self.WgtCheckBox_Out_Sig_PDF = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Sig_PDF.setGeometry(QtCore.QRect(50, 80, 41, 20))
        self.WgtCheckBox_Out_Sig_PDF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Sig_PDF.setChecked(True)
        self.WgtCheckBox_Out_Sig_PDF.setObjectName(_fromUtf8("WgtCheckBox_Out_Sig_PDF"))
        self.WgtCheckBox_Out_Wav_PNG = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Wav_PNG.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.WgtCheckBox_Out_Wav_PNG.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Wav_PNG.setChecked(True)
        self.WgtCheckBox_Out_Wav_PNG.setObjectName(_fromUtf8("WgtCheckBox_Out_Wav_PNG"))
        self.WgtCheckBox_Out_Wav_PDF = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Wav_PDF.setGeometry(QtCore.QRect(120, 80, 41, 20))
        self.WgtCheckBox_Out_Wav_PDF.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Wav_PDF.setChecked(True)
        self.WgtCheckBox_Out_Wav_PDF.setObjectName(_fromUtf8("WgtCheckBox_Out_Wav_PDF"))
        self.WgtCheckBox_Out_Do_Sig = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Do_Sig.setGeometry(QtCore.QRect(20, 20, 61, 20))
        self.WgtCheckBox_Out_Do_Sig.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Do_Sig.setChecked(True)
        self.WgtCheckBox_Out_Do_Sig.setObjectName(_fromUtf8("WgtCheckBox_Out_Do_Sig"))
        self.WgtCheckBox_Out_Sig_PNG = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Sig_PNG.setGeometry(QtCore.QRect(50, 60, 41, 20))
        self.WgtCheckBox_Out_Sig_PNG.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Sig_PNG.setChecked(True)
        self.WgtCheckBox_Out_Sig_PNG.setObjectName(_fromUtf8("WgtCheckBox_Out_Sig_PNG"))
        self.WgtCheckBox_Out_Wav_TXT = QtGui.QCheckBox(self.WgtGroupBox_Wavelet_2)
        self.WgtCheckBox_Out_Wav_TXT.setGeometry(QtCore.QRect(120, 40, 41, 20))
        self.WgtCheckBox_Out_Wav_TXT.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.WgtCheckBox_Out_Wav_TXT.setObjectName(_fromUtf8("WgtCheckBox_Out_Wav_TXT"))
        self.WgtLineEdit_FileName_Out_LBL = QtGui.QLabel(self.WgtGroupBox_Wavelet_2)
        self.WgtLineEdit_FileName_Out_LBL.setGeometry(QtCore.QRect(20, 110, 81, 16))
        self.WgtLineEdit_FileName_Out_LBL.setObjectName(_fromUtf8("WgtLineEdit_FileName_Out_LBL"))
        self.WgtLineEdit_FileName_Out_BASE = QtGui.QLineEdit(self.WgtGroupBox_Wavelet_2)
        self.WgtLineEdit_FileName_Out_BASE.setGeometry(QtCore.QRect(80, 110, 321, 21))
        self.WgtLineEdit_FileName_Out_BASE.setObjectName(_fromUtf8("WgtLineEdit_FileName_Out_BASE"))
        self.WgtWidget_Plot_Convolution = WgtPlot_Wavelet(self.centralWidget)
        self.WgtWidget_Plot_Convolution.setGeometry(QtCore.QRect(450, 310, 511, 111))
        self.WgtWidget_Plot_Convolution.setObjectName(_fromUtf8("WgtWidget_Plot_Convolution"))
        self.WgtPushButton_RUN = QtGui.QPushButton(self.centralWidget)
        self.WgtPushButton_RUN.setGeometry(QtCore.QRect(450, 430, 113, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.WgtPushButton_RUN.setPalette(palette)
        self.WgtPushButton_RUN.setObjectName(_fromUtf8("WgtPushButton_RUN"))
        self.WgtLineEdit_Current_Scale = QtGui.QLineEdit(self.centralWidget)
        self.WgtLineEdit_Current_Scale.setGeometry(QtCore.QRect(820, 430, 61, 20))
        self.WgtLineEdit_Current_Scale.setObjectName(_fromUtf8("WgtLineEdit_Current_Scale"))
        self.WgtLineEdit_Current_Scale_LBL = QtGui.QLabel(self.centralWidget)
        self.WgtLineEdit_Current_Scale_LBL.setGeometry(QtCore.QRect(780, 430, 41, 16))
        self.WgtLineEdit_Current_Scale_LBL.setObjectName(_fromUtf8("WgtLineEdit_Current_Scale_LBL"))
        self.WgtComboBox_ScalogramCBar_1 = QtGui.QComboBox(self.centralWidget)
        self.WgtComboBox_ScalogramCBar_1.setGeometry(QtCore.QRect(910, 430, 131, 26))
        self.WgtComboBox_ScalogramCBar_1.setObjectName(_fromUtf8("WgtComboBox_ScalogramCBar_1"))
        self.WgtComboBox_ScalogramCBar_1.addItem(_fromUtf8(""))
        self.WgtComboBox_ScalogramCBar_1.addItem(_fromUtf8(""))
        UiWaveletPanel.setCentralWidget(self.centralWidget)
        self.WgtMenuBar = QtGui.QMenuBar(UiWaveletPanel)
        self.WgtMenuBar.setGeometry(QtCore.QRect(0, 0, 1064, 18))
        self.WgtMenuBar.setObjectName(_fromUtf8("WgtMenuBar"))
        UiWaveletPanel.setMenuBar(self.WgtMenuBar)
        self.WgtMainToolBar = QtGui.QToolBar(UiWaveletPanel)
        self.WgtMainToolBar.setObjectName(_fromUtf8("WgtMainToolBar"))
        UiWaveletPanel.addToolBar(QtCore.Qt.TopToolBarArea, self.WgtMainToolBar)
        self.WgtStatusBar = QtGui.QStatusBar(UiWaveletPanel)
        self.WgtStatusBar.setObjectName(_fromUtf8("WgtStatusBar"))
        UiWaveletPanel.setStatusBar(self.WgtStatusBar)

        self.retranslateUi(UiWaveletPanel)
        self.WgtTabWidget_Sig.setCurrentIndex(0)
        self.WgtComboBox_Resolution.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UiWaveletPanel)

    def retranslateUi(self, UiWaveletPanel):
        UiWaveletPanel.setWindowTitle(_translate("UiWaveletPanel", "UiWaveletPanel", None))
        self.WgtGroupBox_Wavelet.setTitle(_translate("UiWaveletPanel", "Wavelet Settings", None))
        self.WgtDSpinBox_WavDilStop_LBL.setText(_translate("UiWaveletPanel", "Stop", None))
        self.WgtDSpinBox_WavDilStart_LBL.setText(_translate("UiWaveletPanel", "Start", None))
        self.WgtComboBox_ScaleVsFreq.setItemText(0, _translate("UiWaveletPanel", "Scale", None))
        self.WgtComboBox_ScaleVsFreq.setItemText(1, _translate("UiWaveletPanel", "Frequency", None))
        self.WgtComboBox_WavType.setItemText(0, _translate("UiWaveletPanel", "Morlet - Real", None))
        self.WgtComboBox_WavType.setItemText(1, _translate("UiWaveletPanel", "Morlet - Complex", None))
        self.WgtComboBox_WavType.setItemText(2, _translate("UiWaveletPanel", "Morlet - Imaginary", None))
        self.WgtComboBox_WavType.setItemText(3, _translate("UiWaveletPanel", "Ricker", None))
        self.WgtDSpinBox_WavDilStep_LBL.setText(_translate("UiWaveletPanel", "Step", None))
        self.WgtComboBox_CodeType.setItemText(0, _translate("UiWaveletPanel", "Scipy", None))
        self.WgtComboBox_CodeType.setItemText(1, _translate("UiWaveletPanel", "GN Code", None))
        self.WgtComboBox_CodeType.setItemText(2, _translate("UiWaveletPanel", "GN Code+ CAWT", None))
        self.WgtGroupBox_Sig_2.setTitle(_translate("UiWaveletPanel", "Input Signal ", None))
        self.WgtDSpinBox_Sig1Start_LBL.setText(_translate("UiWaveletPanel", "Start (s)", None))
        self.WgtDSpinBox_Sig1Freq_LBL.setText(_translate("UiWaveletPanel", "Frq 1 ", None))
        self.WgtDSpinBox_Sig1Stop_LBL.setText(_translate("UiWaveletPanel", "Stop (s)", None))
        self.WgtDSpinBox_SigLen_LBL.setText(_translate("UiWaveletPanel", "Length (s)", None))
        self.WgtDSpinBox_SigSmpSec_LBL.setText(_translate("UiWaveletPanel", "Samples / s ", None))
        self.WgtDSpinBox_Sig2Freq_LBL.setText(_translate("UiWaveletPanel", "Frq 2 ", None))
        self.WgtComboBox_Noise.setItemText(0, _translate("UiWaveletPanel", "None", None))
        self.WgtComboBox_Noise.setItemText(1, _translate("UiWaveletPanel", "Random", None))
        self.WgtComboBox_Noise.setItemText(2, _translate("UiWaveletPanel", "White", None))
        self.WgtComboBox_Noise.setItemText(3, _translate("UiWaveletPanel", "Pink", None))
        self.WgtComboBox_Noise_LBL.setText(_translate("UiWaveletPanel", "Noise:", None))
        self.WgtDSpinBox_SigAmp_LBL.setText(_translate("UiWaveletPanel", "Amp", None))
        self.WgtDSpinBox_Sig3Freq_LBL.setText(_translate("UiWaveletPanel", "Frq 3 ", None))
        self.WgtTabWidget_Sig.setTabText(self.WgtTabWidget_Sig.indexOf(self.WgtTabWidget_Page1_SigBuild), _translate("UiWaveletPanel", "Build Sig", None))
        self.WgtLineEdit_FileName_In_LBL.setText(_translate("UiWaveletPanel", "File Name:", None))
        self.WgtPushButton_LoadFileSig.setText(_translate("UiWaveletPanel", "Load File", None))
        self.WgtTabWidget_Sig.setTabText(self.WgtTabWidget_Sig.indexOf(self.WgtTabWidget_Paget_LoadSig), _translate("UiWaveletPanel", "Load File", None))
        self.WgtGroupBox_Wavelet_2.setTitle(_translate("UiWaveletPanel", "Write Settings", None))
        self.WgtPushButton_WriteFiles.setText(_translate("UiWaveletPanel", "Write Files", None))
        self.WgtCheckBox_Out_Sig_TXT.setText(_translate("UiWaveletPanel", "TXT", None))
        self.WgtCheckBox_Out_Do_Wav.setText(_translate("UiWaveletPanel", "Wavelet", None))
        self.WgtComboBox_Resolution.setItemText(0, _translate("UiWaveletPanel", "75", None))
        self.WgtComboBox_Resolution.setItemText(1, _translate("UiWaveletPanel", "150", None))
        self.WgtComboBox_Resolution.setItemText(2, _translate("UiWaveletPanel", "300", None))
        self.WgtComboBox_Resolution.setItemText(3, _translate("UiWaveletPanel", "600", None))
        self.WgtComboBox_Resolution.setItemText(4, _translate("UiWaveletPanel", "1200", None))
        self.WgtComboBox_Resolution_LBL.setText(_translate("UiWaveletPanel", "Resolution:", None))
        self.WgtCheckBox_Out_Sig_PDF.setText(_translate("UiWaveletPanel", "PDF", None))
        self.WgtCheckBox_Out_Wav_PNG.setText(_translate("UiWaveletPanel", "PNG", None))
        self.WgtCheckBox_Out_Wav_PDF.setText(_translate("UiWaveletPanel", "PDF", None))
        self.WgtCheckBox_Out_Do_Sig.setText(_translate("UiWaveletPanel", "Signal", None))
        self.WgtCheckBox_Out_Sig_PNG.setText(_translate("UiWaveletPanel", "PNG", None))
        self.WgtCheckBox_Out_Wav_TXT.setText(_translate("UiWaveletPanel", "TXT", None))
        self.WgtLineEdit_FileName_Out_LBL.setText(_translate("UiWaveletPanel", "File Names:", None))
        self.WgtPushButton_RUN.setText(_translate("UiWaveletPanel", "Generate Scalogram", None))
        self.WgtLineEdit_Current_Scale_LBL.setText(_translate("UiWaveletPanel", "Scale:", None))
        self.WgtComboBox_ScalogramCBar_1.setItemText(0, _translate("UiWaveletPanel", "None", None))
        self.WgtComboBox_ScalogramCBar_1.setItemText(1, _translate("UiWaveletPanel", "Color Bar", None))

from GN_Wavelet_QT_Bindings import WgtPlot_Scalogram, WgtPlot_Wavelet, WgtPlot_Sig1
